### ISSUE TITLE
image.URL is missing board

### ISSUE THREAD

**Issue by ghost** [mtarnawa/godesu#2]
```go
package main

import "github.com/mtarnawa/godesu"

func main() {
    gochan := godesu.New()
    _, thread := gochan.Board("w").GetThread(2147808)

    images := thread.Images()
	for _, image := range images {
	  println(image.URL)
	  println(image.Filename)
	  println(image.Extension)
	  println(image.OriginalFilename)
	}
}
```

Here is a sinnipet of the return

```
00a7a2c5f42f74a7c618401621f3add7.png
https://i.4cdn.org//1599429539169.png
1599429539169.png
```

as you can see this is missing the board, any reason why?

I'm trying to use this to replace an http library with this api, looks a lot simpler and more elegent then how I was trying to do it.

**Comment by mtarnawa** [comment]
Hey, thanks for checking out the project. It's a bit embarrassing, but I forgot to commit all the files. This should now be working as expected. I also tagged the version so you can use v1.0.0 now through go.mod for convenience.

```go

func main() {
	gochan := godesu.New()
	_, thread := gochan.Board("wg").GetThread(7650299)

	images := thread.Images()
	for _, image := range images {
		println(image.URL)
		println(image.Filename)
		println(image.Extension)
		println(image.OriginalFilename)
	}
}

[godesu-test] ./godesu-test                                                                                                                                                          9:58:34 
https://i.4cdn.org/wg/1599455066929.png
1599455066929
.png
(...)
```

**Comment by ghost** [comment]
Thank's for this! I didn't expect you to be so quick to fix this! I have actually implemented this library in a [nice 4chan scraper I made](https://github.com/lordrusk/goscrape). If you wanted to add a `implementations` tab to the readme you could include this, its a really simple implementation so it might be good for people who are learning the library.

**Comment by mtarnawa** [comment]
Sure thing, I'll add it. BTW. perhaps consider using [worker pools](https://gobyexample.com/worker-pools) to control/rate limit simultaneous downloads.

**Comment by ghost** [comment]
it's definetly something I'll look into, I'm starting to get a fork working, as long as I can simulate 1 worker per image, to keep max bandwidth speeds by default but allow the user to cap how many workers at once, I'll most likely implement it. Thanks for the suggestion!
